config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :profiles
  resources :posts do 
    resources :comments 
  end

  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :profile

  validates :content, presence: true, allow_blank: false
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :profile
  has_many :comments
end

app/models/profile.rb
class Profile < ApplicationRecord
    has_one_attached:image
    belongs_to :user
    has_many :posts
    has_many :profile_skills
    has_many :skills, through: :profile_skills

    validates :username, presence: true, allow_blank: false

    validates :image, content_type: /\Aimage\/.*\z/
    validates :image, dimension: { min: 200..100, max: 400..300 }
end

app/models/profile_skill.rb
class ProfileSkill < ApplicationRecord
  belongs_to :profile
  belongs_to :skill
end

app/models/skill.rb
class Skill < ApplicationRecord
    has_many :profile_skills
    has_many :profiles, through: :profile_skills
    validates :name, presence: true
    validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_post, only: [:create, :edit, :update, :destroy]
    before_action :find_comment, only: [:edit, :update, :destroy]

    def new 
    end 

    def create 
        @comment = @post.comments.create(comment_params)
        @comment.profile_id = current_user.profile.id
        if @comment.save 
            redirect_to @post
        else
            flash.now[:error] = "Something went Wrong"
            render 'edit'    
        end
    end

    def edit 
    end

    def update 
        if @comment.update(comment_params)
            redirect_to @post 
        else
            render 'edit'
        end
    end

    def destroy 
        @comment.destroy 
        redirect_to @post
    end

    private 

    def comment_params 
        params.require(:comment).permit(:content)
    end

    def find_post 
        @post = Post.find(params[:post_id])
    end

    def find_comment
        @comment = @post.comments.find(params[:id])
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if user_signed_in? 
      if current_user.profile
        redirect_to profile_path(current_user.profile.id)
      else
        redirect_to new_profile_path 
      end
    end 
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]
    before_action :find_post, only: [:show, :edit, :update, :destroy]

    def index 
        @posts = Post.all.order("created_at DESC")
    end

    def new 
        @post = Post.new 
    end

    def create
        @post = Post.new(post_params)
            if current_user.profile.nil?
                return redirect_to new_profile_path
            else 
                @post.profile_id = current_user.profile.id
            end
        if @post.save 
            redirect_to @post
        else
            render 'new'
        end
    end

    def edit 
        
    end

    def show

    end

    def update 
        if @post.update 
            redirect_to @post
        else 
            flash[:error] = @profile.errors.full_messages.to_sentence
            render 'edit'
        end
    end

    def destroy 
        @post.destroy
        redirect_to posts_path
    end

        



    private 

    def post_params 
        params.require(:post).permit(:title, :body)
    end

    def find_post 
        @post = Post.find(params[:id])
    end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :show, :edit, :update, :destroy]
    before_action :find_profile, only: [:show, :edit, :update, :destroy]

    def index 
        @profiles = Profile.all
    end

    def new 
        @skills = Skill.all
        @profile = Profile.new
    end 

    def create
        @profile = Profile.new(profile_params)
        @profile.user_id = current_user.id
        if @profile.save 
            @profile.skills.build(params[:skill_ids])
            redirect_to @profile
        else
            render 'new'
        end
    end

    def show 
    end

    def edit 
    end 

    def update 
        if @profile.update(profile_params)
            redirect_to profile_path(@profile)
        else
            render 'edit'
        end
    end

    def destroy
        @profile.destroy 
        redirect_to posts_path
    end

    private 

    def profile_params
        params.require(:profile).permit(:username, :description, :role, :image, :skill_ids =>[])
    end

    def find_profile 
        @profile = Profile.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
    <p class="comment-content"><%= comment.content %></p>
    <p class="comment-posted-by">By: <%= comment.profile.username %> <%= time_ago_in_words(comment.created_at)%></p>
    <% if user_signed_in? %>
        <% if current_user.id == comment.profile.user.id %>
            <p><%= link_to 'Edit', edit_post_comment_path(comment.post, comment) %> | <%= link_to 'Delete', post_comment_path(comment.post, comment), method: :delete, data: {confirm: "Are You Sure?"} %> </p>
        <% end %>
    <%end%>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for ([@post, @post.comments.build]), html: {class: "form-group" } do |f| %>
    <%= f.input :content %>
    <%= f.button :submit, class: "btn btn-dark" %>
    <% end %>

app/views/comments/edit.html.erb
<%= simple_form_for ([@post, @comment]), html: {class: "form-group" } do |f| %>
    <%= f.input :content %>
    <%= f.button :submit, class: "btn btn-dark" %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevconnectRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav mr-auto">
             <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to 'DevChat', posts_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Ask A Question?', new_post_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Find A Dev', profiles_path, class: "nav-link" %>
                </li>
             <%else%>
              <li class="nav-item">
                    <%= link_to 'DevChat', posts_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Find A Dev', profiles_path, class: "nav-link" %>
                </li>
             <%end%>
            </ul>
        </div>
        <div class="mx-auto order-0">
            <%= link_to 'DevConnect', root_path, class: "navbar-brand mx-auto" %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ml-auto">
               <% if user_signed_in? %>
                <% if !current_user.profile%>
                 <li class="nav-item">
                    <%= link_to 'Create Your Profile', new_profile_path, class: "nav-link" %>
                </li>
                <%else%>
                 <li class="nav-item">
                    <%= link_to 'Edit Your Profile', edit_profile_path(current_user.profile), class: "nav-link" %>
                </li>
                <%end%>
                <li class="nav-item">
                    <%= link_to 'Account Settings', edit_user_registration_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
                </li>

               <% else %>
                <li class="nav-item">
                    <%= link_to 'Log In', new_user_session_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
                </li>
               <%end %>
            </ul>
        </div>
      </div>
    </nav>
  <div class=container>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%# <% flash.each do |key, value| %>
    <%# <%= content_tag :div, value, class: "alert" %>
    <%# <% end %> 
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/index.html.erb
    <% if user_signed_in? %>
        <% if current_user.profile%>
            <% redirect_to profile_path%>
        <%else%>
            <%redirect_to new_profile_path %>
        <%end%>
    <%end %>



    <div class="jumbotron jumbotron-fluid ">
        <div class="container">
            <h1>Welcome To DevConnect</h1>
            <p class="lead">A Social Media Platform built for devs to ask questions and learn!</p>
            <p><%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-dark btn-lg" %> OR <%= link_to 'Log In', new_user_session_path, class: "btn btn-dark btn-lg" %></p>
        </div>
    </div>

app/views/posts/_form.html.erb
 <%= simple_form_for @post, html: {class: "form-group" } do |f| %>
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.button :submit, class: "btn btn-dark" %>
    <% end %>

app/views/posts/edit.html.erb
<div class="container">
    <h1 class="page-header">Edit Your Post</h1>
    <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post|%>
<div class="row">
  <div class="span8">
    <div class="row">
      <div class="span8">
        <h4><strong><%= post.title %> </strong></h4>
        <i class="icon-user"></i> By: <%= post.profile.username %> 
      </div>
    </div>
    <div class="post-con">
      <div class="span2">
           	<% if post.profile.image.attached?%>
					    <%= image_tag post.profile.image, class: "post-img" %>
					<% else %>
						 <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS52y5aInsxSm31CvHOFHWujqUx_wWTS9iM6s7BAm21oEN_RiGoog" alt=""/>
					<% end%>
      </div>
      <div class="post-text">      
        <p>
        <%= post.body %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="span8">
        <p></p>
        <p>
          <i class="icon-calendar"></i> <%= time_ago_in_words(post.created_at)%>
          | <i class="icon-comment"></i><%= post.comments.count %> Comments
          | <%= link_to 'Read More', post_path(post), class: "btn btn-dark" %>
        </p>
      </div>
    </div>
  </div>
</div>
<%end%>
<hr>

app/views/posts/new.html.erb
<div class="container">
    <h1 class="page-header">Create Your Post</h1>
    <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="col-md-10 col-md-offset-1">
    <div class="message-show">
        <h2><%= @post.title %> </h2>
        <p class="message-posted-by"><%= time_ago_in_words(@post.created_at)%> By <%= @post.profile.username %></p>
        <p class="message-desc"><%= @post.body %></p>

        <div class="links btn-group">
            <%= link_to 'Back', posts_path, class: "btn btn-dark" %>
           
              <% if user_signed_in? %>
               <% if current_user.id == @post.profile.user.id%>
                <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary" %>
                <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: "Are You Sure?"}, class: "btn btn-danger" %>
               <%end%> 
              <%end%>  
        </div>

        <h3 class="comment=selection-header">Comments:</h3>
        <p><%= render @post.comments%> </p>

    <% if user_signed_in? %>
        <h3 class=reply-to-msg>Join Convo</h3>
        <%= render 'comments/form'%>
    <% end%>
 
        
    </div>
</div>

app/views/profiles/_form.html.erb
    <%= simple_form_for @profile, html: {class: "form-group" } do |f| %>
    <%= f.input :username, label: "Select A username" %>
    <%= f.input :description, label: "Tell People about Yourself" %>
    <%= f.input :role, label: "Whats your current Role?"%>
    <%= f.label  "Upload A Profile Pic:"%>
    <%= f.file_field :image, label: "Upload Your Profile Image" %>
    <div class="profiles-con">
    <%= f.label  "What Are your Skills:"%>
    <%= f.collection_check_boxes :skill_ids, Skill.all, :id, :name, { include_hidden: false }, :style => "margin: 10px;"%>
    </div>
    <%= f.button :submit, class: "btn btn-dark" %>
    <% end %>

app/views/profiles/edit.html.erb
<div class="container emp-profile">
    <%= render 'form'%>
</div>

app/views/profiles/index.html.erb
<div class="container-fluid">
	<div class="profiles-con">
        <% @profiles.each do |profile|%>
		<div class="card" style="width: 20rem;">
   					<% if profile.image.attached?%>
					    <%= image_tag profile.image, class: "card-img-top" %>
					<% else %>
						 <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS52y5aInsxSm31CvHOFHWujqUx_wWTS9iM6s7BAm21oEN_RiGoog" alt=""/>
					<% end%>
  <div class="card-block">
    <h4 class="card-title"><%= profile.username %> </h4>
    <p class="card-text"><%= profile.role %></p>
    <%= link_to 'View Profile', profile_path(profile), class: "btn btn-dark" %>
  </div>
</div>
        <%end%>
	</div>
	<br>
	
</div>


		

app/views/profiles/new.html.erb
<div class="container">
    <h1 class="page-header">Create Your Profile</h1>
    <%= render 'form' %>
</div>

app/views/profiles/show.html.erb
<div class="container emp-profile">
             <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img">
                           <% if @profile.image.attached?%>
                                <%= image_tag @profile.image %>    
                            <%else%>
                                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS52y5aInsxSm31CvHOFHWujqUx_wWTS9iM6s7BAm21oEN_RiGoog" alt=""/>
                            <%end%>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h5 class="page-header">
                                        <%= @profile.username %>
                                    </h5>
                                    <h6>
                                        <%= @profile.role %>
                                    </h6>
                        </div>
                    </div>
                    <div class="col-md-2">
                    <% if user_signed_in? %>
                        <%if current_user.profile.id == @profile.id %>
                        <%= link_to 'Edit Your Profile', edit_profile_path, class: "btn btn-dark" %>
                        <%end%>
                    <%end%>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-work">
                            <p>SKILLS</p>
                            <% @profile.skills.each do |skill| %>
                            <p><%= skill.name %></p>
                            <% end %>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                        <div class="row">
                                            <p> <%= @profile.description%>
                                        </div>
                            </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>         
</div>